global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
- job_name: spintron-nn-kit
  static_configs:
  - targets:
    - spintron-api:8081
  metrics_path: /metrics
  scrape_interval: 10s
- job_name: kubernetes-pods
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_scrape
    action: keep
    regex: true