version: '3.8'

services:
  spintron-nn-kit:
    build: 
      context: ../
      dockerfile: containers/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPINTRON_ENV=production
      - SPINTRON_LOG_LEVEL=INFO
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import spintron_nn; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  # Optional: Redis for caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
