apiVersion: apps/v1
kind: Deployment
metadata:
  name: spintron-nn-kit
  labels:
    app: spintron-nn-kit
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spintron-nn-kit
  template:
    metadata:
      labels:
        app: spintron-nn-kit
    spec:
      containers:
      - name: spintron-nn-kit
        image: spintron-nn-kit:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SPINTRON_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: spintron-nn-kit-service
spec:
  selector:
    app: spintron-nn-kit
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
